# Generated by Django 5.0 on 2025-02-03 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Masyarakat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(max_length=16, unique=True)),
                ('nama', models.CharField(max_length=35)),
                ('username', models.CharField(max_length=25, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('telp', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Petugas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_petugas', models.CharField(max_length=35)),
                ('username', models.CharField(max_length=25, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('telp', models.CharField(max_length=13)),
                ('level', models.CharField(choices=[('admin', 'Administrator'), ('petugas', 'Petugas')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pengaduan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_pengaduan', models.DateTimeField(auto_now_add=True)),
                ('isi_laporan', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='pengaduan_foto/')),
                ('status', models.CharField(choices=[('0', 'Belum Diproses'), ('proses', 'Sedang Diproses'), ('selesai', 'Selesai')], default='0', max_length=10)),
                ('nik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pengaduan.masyarakat')),
            ],
        ),
        migrations.CreateModel(
            name='Tanggapan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_tanggapan', models.DateTimeField(auto_now_add=True)),
                ('tanggapan', models.TextField()),
                ('id_pengaduan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pengaduan.pengaduan')),
                ('id_petugas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pengaduan.petugas')),
            ],
        ),
    ]
