# Generated by Django 5.0 on 2025-02-04 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengaduan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masyarakat',
            name='telp',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='petugas',
            name='telp',
            field=models.CharField(max_length=15),
        ),
    ]
